import { upsertOpsBranchFromImport } from "@/lib/branches-store";
import {
  formatBulkImportSummaryAr,
  type BulkImportSummary,
} from "@/lib/csv-excel";
import {
  downloadXlsxTemplate,
  parseSpreadsheetFile,
  parseYesNoAr,
  YES_NO_AR,
} from "@/lib/xlsx-excel";

/**
 * Admin-fillable columns only.
 * `code` is generated by the system and must NOT appear in the template.
 */
export const BRANCH_IMPORT_COLUMNS = [
  "name",
  "city",
  "is_service_center",
  "is_active",
] as const;

export type BranchImportPreviewRow = {
  rowNum: number;
  name: string;
  city: string;
  isServiceCenter: boolean;
  isActive: boolean;
  plannedAction: "create" | "update" | "error";
  error?: string;
};

export type BranchImportPreview = {
  ok: true;
  columns: { key: string; label: string }[];
  rows: BranchImportPreviewRow[];
  validCount: number;
  errorCount: number;
};

const PREVIEW_COLUMNS: { key: string; label: string }[] = [
  { key: "rowNum", label: "صف" },
  { key: "name", label: "اسم الفرع" },
  { key: "city", label: "المدينة" },
  { key: "isServiceCenter", label: "مركز صيانة" },
  { key: "isActive", label: "نشط" },
  { key: "plannedAction", label: "الإجراء" },
  { key: "error", label: "ملاحظة" },
];

export async function downloadBranchesImportTemplate() {
  await downloadXlsxTemplate({
    filename: "arms-branches-template.xlsx",
    sheetName: "فروع",
    columns: [...BRANCH_IMPORT_COLUMNS],
    sampleRow: ["فرع الدمام", "الدمام", "لا", "نعم"],
    dropdowns: [
      { col: 3, header: "is_service_center", list: [...YES_NO_AR] },
      { col: 4, header: "is_active", list: [...YES_NO_AR] },
    ],
    notes: [
      "املأ الاسم والمدينة فقط — كود الفرع يُنشأ تلقائيًا من النظام ولا يظهر في القالب.",
      "مركّز الصيانة والحالة (نشط) تُختار من القوائم المنسدلة (نعم / لا).",
      "المطابقة للتحديث تتم عبر الاسم + المدينة.",
      "لا تغيّر عناوين الأعمدة في الصف الأول.",
    ],
  });
}

export async function previewBranchesImportFile(
  file: File,
): Promise<BranchImportPreview | { ok: false; error: string }> {
  const { headers, rows } = await parseSpreadsheetFile(file);
  if (headers.length === 0) {
    return { ok: false, error: "الملف فارغ أو غير صالح." };
  }
  const required = ["name", "city"];
  const missing = required.filter((col) => !headers.includes(col));
  if (missing.length > 0) {
    return {
      ok: false,
      error: `أعمدة إلزامية ناقصة في القالب: ${missing.join(", ")}`,
    };
  }
  if (rows.length === 0) {
    return { ok: false, error: "لا توجد صفوف بيانات في الملف (بعد صف العناوين)." };
  }

  const { listOpsBranchRecords } = await import("@/lib/branches-store");

  const previewRows: BranchImportPreviewRow[] = rows.map((row, i) => {
    const rowNum = i + 2;
    const name = (row.name ?? "").trim();
    const city = (row.city ?? "").trim();
    const isServiceCenter = parseYesNoAr(row.is_service_center, false);
    const isActive = parseYesNoAr(row.is_active, true);

    let error: string | undefined;
    if (!name || !city) {
      error = "حقول إلزامية ناقصة (name, city).";
    }

    const existing = !error
      ? listOpsBranchRecords({ includeInactive: true }).find(
          (b) => b.name === name && b.city === city,
        )
      : undefined;

    return {
      rowNum,
      name,
      city,
      isServiceCenter,
      isActive,
      plannedAction: error ? "error" : existing ? "update" : "create",
      error,
    };
  });

  return {
    ok: true,
    columns: PREVIEW_COLUMNS,
    rows: previewRows,
    validCount: previewRows.filter((r) => r.plannedAction !== "error").length,
    errorCount: previewRows.filter((r) => r.plannedAction === "error").length,
  };
}

export async function applyBranchesImportPreview(
  rows: BranchImportPreviewRow[],
): Promise<{ ok: true; summary: BulkImportSummary; message: string } | { ok: false; error: string }> {
  const toApply = rows.filter((r) => r.plannedAction !== "error");
  if (toApply.length === 0) {
    return { ok: false, error: "لا توجد صفوف صالحة للتسجيل. راجع الأخطاء في المعاينة." };
  }

  const summary: BulkImportSummary = {
    total: toApply.length,
    created: 0,
    updated: 0,
    failed: 0,
    results: [],
  };

  for (const row of toApply) {
    const result = upsertOpsBranchFromImport({
      name: row.name,
      city: row.city,
      code: null,
      isServiceCenter: row.isServiceCenter,
      isActive: row.isActive,
    });

    if (!result.ok) {
      summary.failed += 1;
      summary.results.push({ row: row.rowNum, ok: false, error: result.error });
      continue;
    }

    if (result.created) {
      summary.created += 1;
      summary.results.push({
        row: row.rowNum,
        ok: true,
        action: "created",
        label: result.branch.code,
      });
    } else {
      summary.updated += 1;
      summary.results.push({
        row: row.rowNum,
        ok: true,
        action: "updated",
        label: result.branch.code,
      });
    }
  }

  return {
    ok: true,
    summary,
    message: formatBulkImportSummaryAr(summary),
  };
}

/** @deprecated Prefer preview + apply flow. */
export async function importBranchesFromCsvFile(
  file: File,
): Promise<{ ok: true; summary: BulkImportSummary; message: string } | { ok: false; error: string }> {
  const preview = await previewBranchesImportFile(file);
  if (!preview.ok) return preview;
  return applyBranchesImportPreview(preview.rows);
}

export function formatBranchPreviewActionAr(
  action: BranchImportPreviewRow["plannedAction"],
): string {
  if (action === "create") return "إنشاء";
  if (action === "update") return "تحديث";
  return "خطأ";
}
