import type {
  Branch,
  Customer,
  DashboardStats,
  Device,
  ServiceRequest,
  SparePart,
} from "@/types/domain";

export const demoCustomers: Customer[] = [
  {
    id: "c1",
    name: "Maison Aroma",
    contactName: "Rania El-Khoury",
    phone: "+961 1 234 567",
    email: "ops@maisonaroma.com",
    address: "Beirut Central District",
    branchCount: 3,
    deviceCount: 18,
  },
  {
    id: "c2",
    name: "Cedar Hotels Group",
    contactName: "Fadi Mansour",
    phone: "+961 4 880 120",
    email: "facilities@cedarhotels.com",
    address: "Dbayeh, Metn",
    branchCount: 5,
    deviceCount: 42,
  },
  {
    id: "c3",
    name: "Olive & Oak Retail",
    contactName: "Sara Daher",
    phone: "+961 3 441 908",
    email: "stores@oliveoak.com",
    address: "Verdun, Beirut",
    branchCount: 4,
    deviceCount: 16,
  },
];

export const demoBranches: Branch[] = [
  {
    id: "b1",
    customerId: "c1",
    customerName: "Maison Aroma",
    name: "BCD Flagship",
    code: "MA-BCD",
    address: "Weygand Street",
    phone: "+961 1 234 567",
  },
  {
    id: "b2",
    customerId: "c1",
    customerName: "Maison Aroma",
    name: "ABC Achrafieh",
    code: "MA-ABC",
    address: "ABC Mall",
    phone: "+961 1 200 300",
  },
  {
    id: "b3",
    customerId: "c2",
    customerName: "Cedar Hotels Group",
    name: "Cedar Grand",
    code: "CH-GRD",
    address: "Dbayeh Highway",
    phone: "+961 4 880 121",
  },
];

export const demoDevices: Device[] = [
  {
    id: "d1",
    deviceCode: "ARMS-10041",
    serialNumber: "SN-88421-A",
    modelName: "Nimbus 300",
    brand: "AromaTech",
    color: "Matte Black",
    customerName: "Maison Aroma",
    branchName: "BCD Flagship",
    status: "under_maintenance",
    currentLocation: "Technician van — Karim",
    qrCode: "ARMS-10041",
  },
  {
    id: "d2",
    deviceCode: "ARMS-10042",
    serialNumber: "SN-88422-B",
    modelName: "Nimbus 300",
    brand: "AromaTech",
    color: "Pearl White",
    customerName: "Maison Aroma",
    branchName: "ABC Achrafieh",
    status: "active",
    currentLocation: "ABC Achrafieh — lobby",
    qrCode: "ARMS-10042",
  },
  {
    id: "d3",
    deviceCode: "ARMS-22010",
    serialNumber: "SN-99102-C",
    modelName: "Vespera Wall",
    brand: "Scentis",
    color: "Brushed Steel",
    customerName: "Cedar Hotels Group",
    branchName: "Cedar Grand",
    status: "sent_to_service_center",
    currentLocation: "Central Service Center",
    qrCode: "ARMS-22010",
  },
  {
    id: "d4",
    deviceCode: "ARMS-22011",
    serialNumber: "SN-99103-D",
    modelName: "Vespera Wall",
    brand: "Scentis",
    color: "Brushed Steel",
    customerName: "Cedar Hotels Group",
    branchName: "Cedar Grand",
    status: "waiting_for_spare_parts",
    currentLocation: "Cedar Grand — spa",
    qrCode: "ARMS-22011",
  },
];

export const demoRequests: ServiceRequest[] = [
  {
    id: "sr1",
    requestNumber: "SR-260927-014",
    customerName: "Maison Aroma",
    branchName: "BCD Flagship",
    deviceCode: "ARMS-10041",
    serialNumber: "SN-88421-A",
    reportedProblem: "Weak diffusion / pump noise",
    deviceCount: 1,
    priority: "high",
    status: "in_progress",
    assignedTechnician: "Karim Saleh",
    requestedAt: "2026-09-26T08:15:00.000Z",
    statusAt: "2026-09-26T10:00:00.000Z",
  },
  {
    id: "sr2",
    requestNumber: "SR-260927-015",
    customerName: "Cedar Hotels Group",
    branchName: "Cedar Grand",
    deviceCode: "ARMS-22010",
    serialNumber: "SN-99102-C",
    reportedProblem: "Board failure after power surge",
    deviceCount: 2,
    priority: "urgent",
    status: "at_service_center",
    assignedTechnician: "Karim Saleh",
    requestedAt: "2026-09-25T11:40:00.000Z",
    statusAt: "2026-09-25T14:20:00.000Z",
  },
  {
    id: "sr3",
    requestNumber: "SR-260926-008",
    customerName: "Cedar Hotels Group",
    branchName: "Cedar Grand",
    deviceCode: "ARMS-22011",
    serialNumber: "SN-99103-D",
    reportedProblem: "Leak at cartridge seal",
    deviceCount: 1,
    priority: "normal",
    status: "waiting_parts",
    assignedTechnician: "Karim Saleh",
    requestedAt: "2026-09-24T09:00:00.000Z",
    statusAt: "2026-09-24T16:30:00.000Z",
  },
  {
    id: "sr4",
    requestNumber: "SR-260924-003",
    customerName: "Olive & Oak Retail",
    branchName: "Verdun",
    deviceCode: "ARMS-31002",
    serialNumber: "SN-31002-E",
    reportedProblem: "Scheduled filter replacement",
    deviceCount: 1,
    priority: "low",
    status: "new",
    assignedTechnician: null,
    requestedAt: "2026-09-27T07:05:00.000Z",
    statusAt: "2026-09-27T07:05:00.000Z",
  },
];

export const demoSpareParts: SparePart[] = [
  {
    id: "p1",
    partCode: "PMP-300",
    name: "Nimbus pump assembly",
    brand: "AromaTech",
    stockQuantity: 6,
    minimumStock: 4,
    unit: "pcs",
  },
  {
    id: "p2",
    partCode: "PCB-VW",
    name: "Vespera control board",
    brand: "Scentis",
    stockQuantity: 1,
    minimumStock: 3,
    unit: "pcs",
  },
  {
    id: "p3",
    partCode: "SEAL-12",
    name: "Cartridge seal 12mm",
    brand: "AromaTech",
    stockQuantity: 48,
    minimumStock: 20,
    unit: "pcs",
  },
];

export const demoStats: DashboardStats = {
  openRequests: 4,
  devicesUnderMaintenance: 3,
  dispatchedDevices: 1,
  lowStockParts: 1,
  activeDevices: 61,
  completedThisMonth: 27,
};
